retrieval:
  top_k: 5 # Number of documents to retrieve
  re_rank: false  # Re-rank documents after retrieval

query_expansion:
  enabled: true
  method: "llm"  # Options: "llm", "synonym", "embedding"
  max_expansion_terms: 3

summarization:
  enabled: false
  method: "density"  # Options: "density", "standard"
  max_iterations: 2

generation:
  model: "tinyllama"
  #max_tokens: 150
  temperature: 0.7

#----AWS code ----
# generation:
#   model: "bedrock"  # Use "bedrock" instead of "tinyllama" or "openai"
#   bedrock_model_id: "amazon.titan-text-express-v1"  # Specific Bedrock model ID
#   #max_tokens: 150
#   temperature: 0.7
#   aws_region: "eu-west-2"  # AWS region where Bedrock is available

# agentic_rag:
#   depth: 3  # Depth of decision-making for agentic RAG
#   retry_limit: 2
