#!/bin/bash
echo "Checking environment variables..."
echo "POSTGRES_USER: $POSTGRES_USER"
echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
echo "POSTGRES_DB: $POSTGRES_DB"
echo "POSTGRES_PORT: $POSTGRES_PORT"
echo "POSTGRES_HOST: $POSTGRES_HOST" 